--
-- PostgreSQL database dump
--

\restrict lamq9mDXwFxY9BieY5KoOzFQV0IhMrukaUEmGNxght2NzVXPd5WLplT00YEvYlg

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: branches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.branches (
    id bigint NOT NULL,
    address character varying(255),
    name character varying(255) NOT NULL,
    phone character varying(255),
    requires_validation boolean DEFAULT true NOT NULL
);


--
-- Name: branches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.branches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.branches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventories (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    branch_id bigint NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: inventories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_exchanges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_exchanges (
    id bigint NOT NULL,
    amount_difference double precision NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    note character varying(255),
    paid_amount double precision NOT NULL,
    quantity integer NOT NULL,
    branch_id bigint NOT NULL,
    new_product_id bigint NOT NULL,
    sale_item_id bigint NOT NULL
);


--
-- Name: product_exchanges_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_exchanges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_exchanges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_returns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_returns (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    quantity integer NOT NULL,
    reason character varying(255),
    branch_id bigint NOT NULL,
    sale_item_id bigint NOT NULL
);


--
-- Name: product_returns_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_returns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_returns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL,
    price double precision NOT NULL,
    category_id bigint
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sale_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sale_items (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    subtotal double precision NOT NULL,
    unit_price double precision NOT NULL,
    product_id bigint NOT NULL,
    sale_id bigint NOT NULL
);


--
-- Name: sale_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sale_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sale_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    total_amount double precision NOT NULL,
    branch_id bigint NOT NULL,
    sold_by_id bigint NOT NULL
);


--
-- Name: sales_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transfers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transfers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    justification character varying(255),
    quantity integer NOT NULL,
    status character varying(255) NOT NULL,
    tracking_code character varying(255),
    updated_at timestamp(6) without time zone,
    dest_branch_id bigint NOT NULL,
    product_id bigint NOT NULL,
    requested_by_id bigint NOT NULL,
    source_branch_id bigint,
    CONSTRAINT transfers_status_check CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'SENT'::character varying, 'RECEIVED'::character varying])::text[])))
);


--
-- Name: transfers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transfers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transfers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    name character varying(255),
    password character varying(255) NOT NULL,
    role character varying(255),
    username character varying(255) NOT NULL,
    branch_id bigint
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: branches; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.branches (id, address, name, phone, requires_validation) FROM stdin;
\.


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.categories (id, name) FROM stdin;
\.


--
-- Data for Name: inventories; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.inventories (id, quantity, branch_id, product_id) FROM stdin;
\.


--
-- Data for Name: product_exchanges; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.product_exchanges (id, amount_difference, created_at, note, paid_amount, quantity, branch_id, new_product_id, sale_item_id) FROM stdin;
\.


--
-- Data for Name: product_returns; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.product_returns (id, created_at, quantity, reason, branch_id, sale_item_id) FROM stdin;
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.products (id, description, name, price, category_id) FROM stdin;
\.


--
-- Data for Name: sale_items; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.sale_items (id, quantity, subtotal, unit_price, product_id, sale_id) FROM stdin;
\.


--
-- Data for Name: sales; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.sales (id, created_at, total_amount, branch_id, sold_by_id) FROM stdin;
\.


--
-- Data for Name: transfers; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.transfers (id, created_at, justification, quantity, status, tracking_code, updated_at, dest_branch_id, product_id, requested_by_id, source_branch_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, name, password, role, username, branch_id) FROM stdin;
1	\N	$2a$10$VuB54WaMpCgMOg2Zi2hFkuGZTIspMx7mk8b9OFQTvAhEgrjeBJwXu	ADMIN	admin	\N
\.


--
-- Name: branches_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.branches_id_seq', 1, false);


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.categories_id_seq', 1, false);


--
-- Name: inventories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.inventories_id_seq', 1, false);


--
-- Name: product_exchanges_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.product_exchanges_id_seq', 1, false);


--
-- Name: product_returns_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.product_returns_id_seq', 1, false);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.products_id_seq', 1, false);


--
-- Name: sale_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sale_items_id_seq', 1, false);


--
-- Name: sales_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sales_id_seq', 1, false);


--
-- Name: transfers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.transfers_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 1, true);


--
-- Name: branches branches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.branches
    ADD CONSTRAINT branches_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: inventories inventories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventories
    ADD CONSTRAINT inventories_pkey PRIMARY KEY (id);


--
-- Name: product_exchanges product_exchanges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_exchanges
    ADD CONSTRAINT product_exchanges_pkey PRIMARY KEY (id);


--
-- Name: product_returns product_returns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_returns
    ADD CONSTRAINT product_returns_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: sale_items sale_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_items
    ADD CONSTRAINT sale_items_pkey PRIMARY KEY (id);


--
-- Name: sales sales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT sales_pkey PRIMARY KEY (id);


--
-- Name: transfers transfers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transfers
    ADD CONSTRAINT transfers_pkey PRIMARY KEY (id);


--
-- Name: branches ukhw68nd07qk3jrjfg70qxq9vb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.branches
    ADD CONSTRAINT ukhw68nd07qk3jrjfg70qxq9vb7 UNIQUE (name);


--
-- Name: inventories ukp5ux0ijhbxmbxcp04ae1t4kdx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventories
    ADD CONSTRAINT ukp5ux0ijhbxmbxcp04ae1t4kdx UNIQUE (branch_id, product_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: categories ukt8o6pivur7nn124jehx7cygw5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: product_exchanges fk2yjnpb6911x0qr2iy7rm939b6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_exchanges
    ADD CONSTRAINT fk2yjnpb6911x0qr2iy7rm939b6 FOREIGN KEY (new_product_id) REFERENCES public.products(id);


--
-- Name: product_exchanges fk3u0r048ab4y3dj4oxlw2trddh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_exchanges
    ADD CONSTRAINT fk3u0r048ab4y3dj4oxlw2trddh FOREIGN KEY (sale_item_id) REFERENCES public.sale_items(id);


--
-- Name: transfers fk6du30e0fkkuuyhn692s6jm52a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transfers
    ADD CONSTRAINT fk6du30e0fkkuuyhn692s6jm52a FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: sales fk79274igjto83cxq8t5ggnlvb2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fk79274igjto83cxq8t5ggnlvb2 FOREIGN KEY (sold_by_id) REFERENCES public.users(id);


--
-- Name: sale_items fk7tcpbc5c5mpnm8fl2phl8ep7l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_items
    ADD CONSTRAINT fk7tcpbc5c5mpnm8fl2phl8ep7l FOREIGN KEY (sale_id) REFERENCES public.sales(id);


--
-- Name: transfers fk83r0km497n7qro5myh4p8n4ee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transfers
    ADD CONSTRAINT fk83r0km497n7qro5myh4p8n4ee FOREIGN KEY (dest_branch_id) REFERENCES public.branches(id);


--
-- Name: inventories fk8drmqyx629j3oo8ct9jnc5y3y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventories
    ADD CONSTRAINT fk8drmqyx629j3oo8ct9jnc5y3y FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: sale_items fk8g0sjiqs7tg055o06p6wawu39; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_items
    ADD CONSTRAINT fk8g0sjiqs7tg055o06p6wawu39 FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: users fk9o70sp9ku40077y38fk4wieyk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk9o70sp9ku40077y38fk4wieyk FOREIGN KEY (branch_id) REFERENCES public.branches(id);


--
-- Name: inventories fkgs563w23gys2co425wraxaj1o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventories
    ADD CONSTRAINT fkgs563w23gys2co425wraxaj1o FOREIGN KEY (branch_id) REFERENCES public.branches(id);


--
-- Name: product_returns fkk268rqady4fmxb2qsdiv14ujh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_returns
    ADD CONSTRAINT fkk268rqady4fmxb2qsdiv14ujh FOREIGN KEY (branch_id) REFERENCES public.branches(id);


--
-- Name: product_returns fkmep1c2scyyb59x1cfyc7el060; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_returns
    ADD CONSTRAINT fkmep1c2scyyb59x1cfyc7el060 FOREIGN KEY (sale_item_id) REFERENCES public.sale_items(id);


--
-- Name: product_exchanges fko3gtr8meu1ncv7tmd236r2wh8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_exchanges
    ADD CONSTRAINT fko3gtr8meu1ncv7tmd236r2wh8 FOREIGN KEY (branch_id) REFERENCES public.branches(id);


--
-- Name: products fkog2rp4qthbtt2lfyhfo32lsw9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: transfers fkpfg3dqbhov1b558jdal2lq77s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transfers
    ADD CONSTRAINT fkpfg3dqbhov1b558jdal2lq77s FOREIGN KEY (source_branch_id) REFERENCES public.branches(id);


--
-- Name: sales fkrhimhek4ehsu31ujgod41qnhx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fkrhimhek4ehsu31ujgod41qnhx FOREIGN KEY (branch_id) REFERENCES public.branches(id);


--
-- Name: transfers fks8bokm8pxq4s3mrbyvepyeyoc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transfers
    ADD CONSTRAINT fks8bokm8pxq4s3mrbyvepyeyoc FOREIGN KEY (requested_by_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict lamq9mDXwFxY9BieY5KoOzFQV0IhMrukaUEmGNxght2NzVXPd5WLplT00YEvYlg

